version: "3.9"
services:
  scrapy:
    build: .
    # command: "scrapy"
    command: "tail -f /dev/null"
    volumes:
      - .:/app
    ports:
      - "6800:6800"
    # depends_on:
    #   - mongodb